apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05716abfba96e3d09

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: ebs-static
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: efs-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-claim


---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007
